server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydatabase.cc5cpcgh917t.ap-northeast-2.rds.amazonaws.com:3306/playbebe
    username: admin
    password: qor5679177

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  jackson:
    serialization:
      fail-on-empty-beans: false

file:
  #path: C:/KnuImages/
  path: /home/ec2-user/KnuImages/